<?php return array (
  'site_title' => '5glogistic',
  'base_color' => '403b87',
  'time_zone' => 'Asia/Jakarta',
  'currency' => 'IDR',
  'currency_symbol' => 'Rp',
  'theme' => '5glogistic',
  'fraction_number' => 0,
  'paginate' => 10,
  'email_verification' => 0,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'investment_commission' => 1,
  'deposit_commission' => 0,
  'sender_email' => 'intan@perhiasanintan.com',
  'sender_email_name' => 'PerhiasanIntan',
  'email_description' => '"<meta charset=\\"UTF-8\\">\\r\\n  <link rel=\\"preconnect\\" href=\\"https:\\/\\/fonts.googleapis.com\\">\\r\\n  <link rel=\\"preconnect\\" href=\\"https:\\/\\/fonts.gstatic.com\\" crossorigin=\\"\\">\\r\\n  <link href=\\"https:\\/\\/fonts.googleapis.com\\/css2?family=Dosis:wght@400;500;600;700;800&display=swap\\" rel=\\"stylesheet\\">\\r\\n\\r\\n  <style type=\\"text\\/css\\">\\r\\n    @import url(\\"https:\\/\\/fonts.googleapis.com\\/css2?family=Dosis:wght@400;500;600;700;800&display=swap\\");\\r\\n    body{\\r\\n      font-family: \\"Dosis\\", sans-serif; color: black;\\r\\n    }\\r\\n      p, h1, h2, h3, h4, ol, li, ul, a { font-family: \\"Dosis\\", sans-serif; color: black;}\\r\\n      table th, td{\\r\\n        padding: 5px 15px 5px 0px;\\r\\n      }\\r\\n      p{\\r\\n        margin-bottom: 3px;\\r\\n      }\\r\\n    <\\/style>\\r\\n\\r\\n\\r\\n  <div style=\\" padding: 50px 0px 0px; overflow: hidden; background: white; border-radius: 10px; max-width: 70%; margin: 0px auto; border-top: 3px solid #be9277;\\">\\r\\n    <div style=\\"padding: 0px 30px;\\">\\r\\n      <div style=\\"text-align: center; border-bottom: 1px solid #be9277;\\">\\r\\n        <a href=\\"#\\">\\r\\n          <img src=\\"https:\\/\\/perhiasanintan.com\\/intan\\/assets\\/frontend\\/intan\\/img\\/logo.png\\" alt=\\"logo\\" width=\\"200px\\">\\r\\n        <\\/a>\\r\\n      <\\/div>\\r\\n    <\\/div>\\r\\n    <div style=\\"text-align: left; border-radius: 5px; padding: 10px 0px; margin: 0px 30px;\\">\\r\\n      <h3>Hello, [[name]]<\\/h3>\\r\\n      <p>[[message]]<\\/p>\\r\\n      <br>\\r\\n    <\\/div>\\r\\n    <div style=\\"text-align: center; margin-top: 20px; background: #644d3f;  padding-top: 10px; padding-bottom: 10px; color: white;\\">\\r\\n      <table align=\\"center\\">\\r\\n        <tbody><tr><td><a href=\\"https:\\/\\/perhiasanintan.com\\" style=\\"text-decoration: none; color: white; font-size: 13px;\\">perhiasanintan.com<\\/a><\\/td>\\r\\n        <td><span style=\\"color: white; font-size: 13px;\\">|<\\/span><\\/td>\\r\\n        <td><a href=\\"mailto:\\/\\/info@perhiasanintan.com\\" style=\\"text-decoration: none; color: white; font-size: 13px;\\">info@perhiasanintan.com<\\/a><\\/td>\\r\\n      <\\/tr><\\/tbody><\\/table>\\r\\n      <div style=\\"text-align: center; padding-top: 0px; margin-top: 0px; \\">\\r\\n        <p style=\\"font-size: 13px; color: white;\\">perhiasanintan all right reserved \\u00a9 2023<\\/p>\\r\\n      <\\/div>\\r\\n    <\\/div>\\r\\n  <\\/div>"',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'perhiasanintan.com',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'intan@perhiasanintan.com',
    'smtp_password' => 'lIhyZjsdDLCQ',
  ),
  'push_notification' => 0,
  'min_transfer' => '500.00',
  'max_transfer' => '900000.00',
  'transfer_charge' => '0',
  'bonus_amount' => '10000',
  'joining_bonus' => 1,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 0,
);